const { executeQuery } = require("../utils/queryExecutor");
/*
-- Generated by the database client.
CREATE TABLE coins(
    coin_id varchar(255) NOT NULL,
    coin_type_legacy varchar(255),
    coin_address_fungible varchar(255),
    coin_name varchar(255),
    coin_symbol varchar(255),
    coin_defyapp_symbol varchar(255),
    coin_decimals integer NOT NULL,
    coin_description text,
    coin_logo_url varchar(255),
    coingecko_id varchar(255),
    coinmarketcap_id varchar(255),
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    PRIMARY KEY(coin_id)
);
*/

const addCoinIfNotExists = async (coinData) => {
  const query = `
    INSERT INTO coins (coin_id, coin_type_legacy, coin_address_fungible, coin_name, coin_symbol, coin_defyapp_symbol, coin_decimals, coin_description, coin_logo_url, coingecko_id, coinmarketcap_id)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
    ON CONFLICT (coin_id)
    DO NOTHING
    RETURNING *;
  `;
  return executeQuery(
    query,
    [
      coinData.coin_id,
      coinData.coin_type_legacy,
      coinData.coin_address_fungible,
      coinData.coin_name,
      coinData.coin_symbol,
      coinData.coin_defyapp_symbol,
      coinData.coin_decimals,
      coinData.coin_description,
      coinData.coin_logo_url,
      coinData.coingecko_id,
      coinData.coinmarketcap_id,
    ],
    true
  );
};

const addMultipleCoins = async (coinsData) => {
  const query = `
    INSERT INTO coins (coin_id, coin_type_legacy, coin_address_fungible, coin_name, coin_symbol, coin_defyapp_symbol, coin_decimals, coin_description, coin_logo_url, coingecko_id, coinmarketcap_id)
    VALUES ${coinsData
      .map(
        (_, index) =>
          `($${index * 11 + 1}, $${index * 11 + 2}, $${index * 11 + 3}, $${
            index * 11 + 4
          }, $${index * 11 + 5}, $${index * 11 + 6}, $${index * 11 + 7}, $${
            index * 11 + 8
          }, $${index * 11 + 9}, $${index * 11 + 10}, $${index * 11 + 11})`
      )
      .join(", ")}
    ON CONFLICT (coin_id)
    DO NOTHING
    RETURNING *;
  `;
  const values = coinsData.reduce((acc, coin) => {
    acc.push(coin.coin_id);
    acc.push(coin.coin_type_legacy);
    acc.push(coin.coin_address_fungible);
    acc.push(coin.coin_name);
    acc.push(coin.coin_symbol);
    acc.push(coin.coin_defyapp_symbol);
    acc.push(coin.coin_decimals);
    acc.push(coin.coin_description);
    acc.push(coin.coin_logo_url);
    acc.push(coin.coingecko_id);
    acc.push(coin.coinmarketcap_id);
    return acc;
  }, []);
  return executeQuery(query, values, true);
};

// addmultiple coins and update on conflict
const addMultipleCoinsOrUpdate = async (coinsData) => {
  const query = `
    INSERT INTO coins (coin_id, coin_type_legacy, coin_address_fungible, coin_name, coin_symbol, coin_defyapp_symbol, coin_decimals, coin_description, coin_logo_url, coingecko_id, coinmarketcap_id)
    VALUES ${coinsData
      .map(
        (_, index) =>
          `($${index * 11 + 1}, $${index * 11 + 2}, $${index * 11 + 3}, $${
            index * 11 + 4
          }, $${index * 11 + 5}, $${index * 11 + 6}, $${index * 11 + 7}, $${
            index * 11 + 8
          }, $${index * 11 + 9}, $${index * 11 + 10}, $${index * 11 + 11})`
      )
      .join(", ")}
    ON CONFLICT (coin_id)
    DO UPDATE SET
      coin_type_legacy = excluded.coin_type_legacy,
      coin_address_fungible = excluded.coin_address_fungible,
      coin_name = excluded.coin_name,
      coin_symbol = excluded.coin_symbol,
      coin_defyapp_symbol = excluded.coin_defyapp_symbol,
      coin_decimals = excluded.coin_decimals,
      coin_description = excluded.coin_description,
      coin_logo_url = excluded.coin_logo_url,
      coingecko_id = excluded.coingecko_id,
      coinmarketcap_id = excluded.coinmarketcap_id,
      updated_at = NOW()
    RETURNING *;
  `;
  const values = coinsData.reduce((acc, coin) => {
    acc.push(coin.coin_id);
    acc.push(coin.coin_type_legacy);
    acc.push(coin.coin_address_fungible);
    acc.push(coin.coin_name);
    acc.push(coin.coin_symbol);
    acc.push(coin.coin_defyapp_symbol);
    acc.push(coin.coin_decimals);
    acc.push(coin.coin_description);
    acc.push(coin.coin_logo_url);
    acc.push(coin.coingecko_id);
    acc.push(coin.coinmarketcap_id);
    return acc;
  }, []);
  return executeQuery(query, values, true);
};

const updateCoin = async (coinId, coinData) => {
  const query = `
    UPDATE coins
    SET coin_type_legacy = $1,
        coin_address_fungible = $2,
        coin_name = $3,
        coin_symbol = $4,
        coin_defyapp_symbol = $5,
        coin_decimals = $6,
        coin_description = $7,
        coin_logo_url = $8,
        coingecko_id = $9,
        coinmarketcap_id = $10,
        updated_at = NOW()
    WHERE coin_id = $11
    RETURNING *;
  `;
  return executeQuery(
    query,
    [
      coinData.coin_type_legacy,
      coinData.coin_address_fungible,
      coinData.coin_name,
      coinData.coin_symbol,
      coinData.coin_defyapp_symbol,
      coinData.coin_decimals,
      coinData.coin_description,
      coinData.coin_logo_url,
      coinData.coingecko_id,
      coinData.coinmarketcap_id,
      coinId,
    ],
    true
  );
};

// get functions

const getCoinById = async (coinId) => {
  const query = `
    SELECT * FROM coins WHERE coin_id = $1;
  `;
  return executeQuery(query, [coinId]);
};

const getAllCoins = async () => {
  const query = `
    SELECT * FROM coins;
  `;
  return executeQuery(query);
};

module.exports = {
  addCoinIfNotExists,
  getAllCoins,
  getCoinById,
  updateCoin,
  addMultipleCoins,
  addMultipleCoinsOrUpdate,
};
