CREATE TABLE IF NOT EXISTS coin_metrics (
        coin_id VARCHAR(255) PRIMARY KEY REFERENCES coins(coin_id),
        circulating_supply NUMERIC NULL,
        total_supply NUMERIC NULL,
        max_supply NUMERIC NULL,
        holders NUMERIC NULL,
        infinite_supply BOOLEAN NULL,
        self_reported_market_cap NUMERIC NULL,
        self_reported_circulating_supply NUMERIC NULL,
        price_usd NUMERIC NULL,
        price_change_5m NUMERIC NULL,
        price_change_1hr NUMERIC NULL,
        price_change_6hr NUMERIC NULL,
        price_change_24h NUMERIC NULL,
        price_change_7d NUMERIC NULL,
        price_change_30d NUMERIC NULL,
        volume_24hr NUMERIC NULL,
        volume_7d NUMERIC NULL,
        volume_30d NUMERIC NULL,
        volume_change_24hr NUMERIC NULL,
        market_cap NUMERIC NULL,
        fully_diluted_market_cap NUMERIC NULL,
        merket_cap_by_total_supply NUMERIC NULL,
        tvl NUMERIC NULL,
        raw_charts JSONB NULL,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        updated_at TIMESTAMPTZ DEFAULT NOW()
)