CREATE TABLE IF NOT EXISTS uptos_pump_legend (
    id SERIAL PRIMARY KEY,
    addr TEXT NOT NULL UNIQUE,
    nsfw BOOLEAN DEFAULT FALSE,
    img TEXT,
    name TEXT,
    ticker TEXT,
    description TEXT,
    twitter TEXT,
    telegram TEXT,
    website TEXT,
    virtual_aptos_reserves TEXT,
    virtual_token_reserves TEXT,
    initial_token_reserves TEXT,
    rep_count INTEGER,
    created_by TEXT,
    bonding_curve TEXT,
    created_at TIMESTAMPTZ,
    tx_at TIMESTAMPTZ,
    tx_count INTEGER,
    rep_at TIMESTAMPTZ,
    legend_at TIMESTAMPTZ,
    legend_tx TEXT,
    completed_at TIMESTAMPTZ,
    completed_tx TEXT,
    lp_addr TEXT,
    user_addr TEXT,
    user_name TEXT,
    user_img TEXT,
    market_cap NUMERIC,
    created_db_at TIMESTAMPTZ DEFAULT NOW(),
    updated_db_at TIMESTAMPTZ DEFAULT NOW()
);